# Generated by Django 3.1.3 on 2020-12-06 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('contact_number', models.IntegerField(blank=True, unique=True)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betting_amount', models.IntegerField(default=0)),
                ('room_code', models.CharField(max_length=1000)),
                ('is_true', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.IntegerField()),
                ('available_coins', models.IntegerField(default=0)),
                ('term_condition', models.BooleanField(default=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_on', models.DateTimeField(auto_now=True, null=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('referral_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sell_coins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paytm_number', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('processed_on', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_slug', models.CharField(max_length=1000)),
                ('game_status', models.CharField(max_length=100)),
                ('game_amount', models.IntegerField(default=50)),
                ('firebase_id', models.CharField(blank=True, max_length=400)),
                ('game_created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='static/gameimages')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ludoapp.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_start', to='ludoapp.gamestart'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='user_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='user_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_two', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BetTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('requested_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('transaction_status', models.BooleanField(blank=True, choices=[(True, 'success'), (False, 'failed')], default=False, null=True, verbose_name='Transaction Status')),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transaction On')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='better', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Add_coins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transection_id', models.CharField(max_length=250)),
                ('amount', models.FloatField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
