# Generated by Django 2.2.1 on 2020-11-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='whatsap_number',
            new_name='whatsapp_number',
        ),
    ]
