# Generated by Django 3.1.3 on 2020-12-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettransaction',
            name='game_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
