# Generated by Django 3.1.3 on 2020-11-28 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ludoapp', '0003_auto_20201128_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_coins',
            name='paytm_number',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='BetTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField()),
                ('game_name', models.CharField(max_length=50)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Transaction On')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='better', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
