# Generated by Django 3.1.3 on 2020-11-28 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ludoapp', '0004_auto_20201128_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettransaction',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transaction On'),
        ),
    ]
