# Generated by Django 3.1.3 on 2020-12-08 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoapp', '0005_auto_20201208_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercoins',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
