# Generated by Django 3.1.3 on 2020-11-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoapp', '0006_auto_20201128_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettransaction',
            name='transaction_status',
            field=models.BooleanField(default=False, verbose_name='Transaction Status'),
        ),
    ]
