# Generated by Django 3.1.3 on 2020-12-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoapp', '0006_ordercoins_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercoins',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
