# Generated by Django 3.1.3 on 2020-11-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoapp', '0007_bettransaction_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettransaction',
            name='transaction_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Transaction Status'),
        ),
    ]
