# Generated by Django 3.1.3 on 2020-12-09 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludoapp', '0008_penalty_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='flagged_as_disputed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='result_user_one',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='result_user_two',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DisputedGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_disputed', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ludoapp.game')),
            ],
        ),
    ]
