# Generated by Django 3.1.3 on 2020-12-09 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ludoapp', '0009_auto_20201209_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='user_one',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_two',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
