# Generated by Django 3.1.3 on 2020-11-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoapp', '0009_auto_20201129_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='available_coins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
