# Generated by Django 3.1.3 on 2020-12-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoapp', '0010_user_info_available_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
