# Generated by Django 3.1.3 on 2020-12-13 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ludoapp', '0016_auto_20201213_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettransaction',
            name='requested_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 9, 1, 59, 551718, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='whatsapp_number',
            field=models.CharField(max_length=30),
        ),
    ]
