# Generated by Django 3.1.3 on 2020-12-13 15:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ludoapp', '0017_auto_20201213_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_over',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bettransaction',
            name='requested_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 15, 1, 40, 508719, tzinfo=utc), null=True),
        ),
    ]
